import { memo } from 'react'
import {
  SiAstro,
  SiBabel,
  SiBlender,
  SiBun,
  SiC,
  SiClojure,
  SiCmake,
  SiCplusplus,
  SiCss,
  SiCrystal,
  SiDart,
  SiDeno,
  SiDocker,
  SiDocusaurus,
  SiDotnet,
  SiEditorconfig,
  SiElectron,
  SiElixir,
  SiElm,
  SiErlang,
  SiEslint,
  SiFigma,
  SiFortran,
  SiFsharp,
  SiGatsby,
  SiGit,
  SiGitlab,
  SiGnubash,
  SiGo,
  SiGodotengine,
  SiGradle,
  SiGraphql,
  SiGrunt,
  SiGulp,
  SiHandlebarsdotjs,
  SiHaskell,
  SiHtml5,
  SiHugo,
  SiJavascript,
  SiJekyll,
  SiJenkins,
  SiJson,
  SiJupyter,
  SiKotlin,
  SiLatex,
  SiLess,
  SiLua,
  SiMarkdown,
  SiNextdotjs,
  SiNim,
  SiNodedotjs,
  SiNpm,
  SiOcaml,
  SiOpenjdk,
  SiPerl,
  SiPhp,
  SiPnpm,
  SiPostcss,
  SiPostgresql,
  SiPrettier,
  SiPrisma,
  SiPug,
  SiPython,
  SiPypi,
  SiR,
  SiReact,
  SiRemix,
  SiRuby,
  SiRust,
  SiSass,
  SiScala,
  SiSharp,
  SiSketch,
  SiSqlite,
  SiStylus,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
  SiVim,
  SiVite,
  SiVitest,
  SiVuedotjs,
  SiWebassembly,
  SiWebpack,
  SiYaml,
  SiYarn,
  SiZig
} from 'react-icons/si'
import {
  Archive,
  Database,
  File,
  FileText,
  Image,
  Lock,
  Music,
  Settings,
  Video
} from 'lucide-react'

interface IconConfig {
  Icon: React.ComponentType<{
    size?: number
    className?: string
    style?: React.CSSProperties
  }>
  color: string
}

const iconMap: Record<string, IconConfig> = {
  js: { Icon: SiJavascript, color: '#F7DF1E' },
  mjs: { Icon: SiJavascript, color: '#F7DF1E' },
  cjs: { Icon: SiJavascript, color: '#F7DF1E' },
  jsx: { Icon: SiReact, color: '#61DAFB' },
  ts: { Icon: SiTypescript, color: '#3178C6' },
  tsx: { Icon: SiReact, color: '#61DAFB' },
  py: { Icon: SiPython, color: '#3776AB' },
  pyw: { Icon: SiPython, color: '#3776AB' },
  cs: { Icon: SiSharp, color: '#239120' },
  csproj: { Icon: SiDotnet, color: '#512BD4' },
  java: { Icon: SiOpenjdk, color: '#437291' },
  go: { Icon: SiGo, color: '#00ADD8' },
  rs: { Icon: SiRust, color: '#DEA584' },
  c: { Icon: SiC, color: '#A8B9CC' },
  h: { Icon: SiC, color: '#A8B9CC' },
  cpp: { Icon: SiCplusplus, color: '#00599C' },
  cc: { Icon: SiCplusplus, color: '#00599C' },
  cxx: { Icon: SiCplusplus, color: '#00599C' },
  hpp: { Icon: SiCplusplus, color: '#00599C' },
  php: { Icon: SiPhp, color: '#777BB4' },
  rb: { Icon: SiRuby, color: '#CC342D' },
  html: { Icon: SiHtml5, color: '#E34F26' },
  htm: { Icon: SiHtml5, color: '#E34F26' },
  css: { Icon: SiCss, color: '#1572B6' },
  scss: { Icon: SiSass, color: '#CC6699' },
  sass: { Icon: SiSass, color: '#CC6699' },
  json: { Icon: SiJson, color: '#000000' },
  jsonc: { Icon: SiJson, color: '#000000' },
  yml: { Icon: SiYaml, color: '#CB171E' },
  yaml: { Icon: SiYaml, color: '#CB171E' },
  md: { Icon: SiMarkdown, color: '#083fa1' },
  mdx: { Icon: SiMarkdown, color: '#083fa1' },
  sh: { Icon: SiGnubash, color: '#4EAA25' },
  bash: { Icon: SiGnubash, color: '#4EAA25' },
  zsh: { Icon: SiGnubash, color: '#4EAA25' },
  fish: { Icon: SiGnubash, color: '#4EAA25' },
  sql: { Icon: SiPostgresql, color: '#336791' },
  db: { Icon: Database, color: '#336791' },
  sqlite: { Icon: SiSqlite, color: '#003B57' },
  swift: { Icon: SiSwift, color: '#F05138' },
  kt: { Icon: SiKotlin, color: '#7F52FF' },
  dart: { Icon: SiDart, color: '#0175C2' },
  lua: { Icon: SiLua, color: '#2C2D72' },
  r: { Icon: SiR, color: '#276DC3' },
  ex: { Icon: SiElixir, color: '#4B275F' },
  exs: { Icon: SiElixir, color: '#4B275F' },
  fs: { Icon: SiFsharp, color: '#b845fc' },
  hs: { Icon: SiHaskell, color: '#5D4F85' },
  clj: { Icon: SiClojure, color: '#5881D8' },
  scala: { Icon: SiScala, color: '#DC322F' },
  erl: { Icon: SiErlang, color: '#A90533' },
  ml: { Icon: SiOcaml, color: '#3BE133' },
  vue: { Icon: SiVuedotjs, color: '#4FC08D' },
  svelte: { Icon: SiSvelte, color: '#FF3E00' },
  graphql: { Icon: SiGraphql, color: '#E10098' },
  gql: { Icon: SiGraphql, color: '#E10098' },
  yarn: { Icon: SiYarn, color: '#2C8EBB' },
  npm: { Icon: SiNpm, color: '#CB3837' },
  pnpm: { Icon: SiPnpm, color: '#F69220' },
  vite: { Icon: SiVite, color: '#646CFF' },
  astro: { Icon: SiAstro, color: '#FF5D01' },
  wasm: { Icon: SiWebassembly, color: '#654FF0' },
  gd: { Icon: SiGodotengine, color: '#478CBF' },
  vim: { Icon: SiVim, color: '#019733' },
  lock: { Icon: Lock, color: '#9ca3af' },
  png: { Icon: Image, color: '#10b981' },
  jpg: { Icon: Image, color: '#10b981' },
  jpeg: { Icon: Image, color: '#10b981' },
  gif: { Icon: Image, color: '#10b981' },
  bmp: { Icon: Image, color: '#10b981' },
  webp: { Icon: Image, color: '#10b981' },
  ico: { Icon: Image, color: '#10b981' },
  svg: { Icon: Image, color: '#f59e0b' },
  mp4: { Icon: Video, color: '#ec4899' },
  mkv: { Icon: Video, color: '#ec4899' },
  avi: { Icon: Video, color: '#ec4899' },
  mov: { Icon: Video, color: '#ec4899' },
  mp3: { Icon: Music, color: '#8b5cf6' },
  wav: { Icon: Music, color: '#8b5cf6' },
  flac: { Icon: Music, color: '#8b5cf6' },
  zip: { Icon: Archive, color: '#f59e0b' },
  rar: { Icon: Archive, color: '#f59e0b' },
  '7z': { Icon: Archive, color: '#f59e0b' },
  tar: { Icon: Archive, color: '#f59e0b' },
  gz: { Icon: Archive, color: '#f59e0b' },
  pdf: { Icon: FileText, color: '#ef4444' },
  txt: { Icon: FileText, color: '#6b7280' },
  env: { Icon: Settings, color: '#ecd53f' },
  ini: { Icon: Settings, color: '#ecd53f' },
  conf: { Icon: Settings, color: '#ecd53f' },
  toml: { Icon: FileText, color: '#9c4221' },
  xml: { Icon: FileText, color: '#f97316' },
  fig: { Icon: SiFigma, color: '#F24E1E' },
  sketch: { Icon: SiSketch, color: '#F7B500' },
  blend: { Icon: SiBlender, color: '#EA7600' },
  mts: { Icon: SiTypescript, color: '#3178C6' },
  cts: { Icon: SiTypescript, color: '#3178C6' },
  phtml: { Icon: SiPhp, color: '#777BB4' },
  php3: { Icon: SiPhp, color: '#777BB4' },
  php4: { Icon: SiPhp, color: '#777BB4' },
  php5: { Icon: SiPhp, color: '#777BB4' },
  phps: { Icon: SiPhp, color: '#777BB4' },
  erb: { Icon: SiRuby, color: '#CC342D' },
  rake: { Icon: SiRuby, color: '#CC342D' },
  gemspec: { Icon: SiRuby, color: '#CC342D' },
  fsx: { Icon: SiFsharp, color: '#b845fc' },
  fsproj: { Icon: SiDotnet, color: '#512BD4' },
  vbproj: { Icon: SiDotnet, color: '#512BD4' },
  sln: { Icon: SiDotnet, color: '#512BD4' },
  wat: { Icon: SiWebassembly, color: '#654FF0' },
  pl: { Icon: SiPerl, color: '#39457E' },
  pm: { Icon: SiPerl, color: '#39457E' },
  properties: { Icon: SiOpenjdk, color: '#437291' },
  tex: { Icon: SiLatex, color: '#008080' },
  bib: { Icon: SiLatex, color: '#008080' },
  graphqls: { Icon: SiGraphql, color: '#E10098' },
  prisma: { Icon: SiPrisma, color: '#2D3748' },
  zig: { Icon: SiZig, color: '#F7A41D' },
  nim: { Icon: SiNim, color: '#FFE953' },
  cr: { Icon: SiCrystal, color: '#000000' },
  f: { Icon: SiFortran, color: '#734F96' },
  f90: { Icon: SiFortran, color: '#734F96' },
  f95: { Icon: SiFortran, color: '#734F96' },
  for: { Icon: SiFortran, color: '#734F96' },
  kts: { Icon: SiKotlin, color: '#7F52FF' },
  gradle: { Icon: SiGradle, color: '#02303A' },
  cmake: { Icon: SiCmake, color: '#064F8C' },
  elm: { Icon: SiElm, color: '#60B5CC' },
  cljc: { Icon: SiClojure, color: '#5881D8' },
  cljs: { Icon: SiClojure, color: '#5881D8' },
  edn: { Icon: SiClojure, color: '#5881D8' },
  hrl: { Icon: SiErlang, color: '#A90533' },
  mli: { Icon: SiOcaml, color: '#3BE133' },
  rmd: { Icon: SiR, color: '#276DC3' },
  ipynb: { Icon: SiJupyter, color: '#F37626' },
  tf: { Icon: SiTerraform, color: '#7B42BC' },
  tfvars: { Icon: SiTerraform, color: '#7B42BC' },
  tfstate: { Icon: SiTerraform, color: '#7B42BC' },
  hcl: { Icon: SiTerraform, color: '#7B42BC' },
  less: { Icon: SiLess, color: '#1D365D' },
  styl: { Icon: SiStylus, color: '#333333' },
  hbs: { Icon: SiHandlebarsdotjs, color: '#000000' },
  pug: { Icon: SiPug, color: '#A86454' },
  patch: { Icon: SiGit, color: '#F05032' },
  diff: { Icon: SiGit, color: '#F05032' },
  jar: { Icon: SiOpenjdk, color: '#437291' },
  war: { Icon: SiOpenjdk, color: '#437291' },
  whl: { Icon: SiPypi, color: '#3775A9' },
  gem: { Icon: SiRuby, color: '#CC342D' },
  crate: { Icon: SiRust, color: '#DEA584' },
  csv: { Icon: FileText, color: '#6b7280' },
  tsv: { Icon: FileText, color: '#6b7280' },
  log: { Icon: FileText, color: '#6b7280' }
}

const filenameMap: Record<string, IconConfig> = {
  dockerfile: { Icon: SiDocker, color: '#2496ED' },
  makefile: { Icon: FileText, color: '#a3a3a3' },
  license: { Icon: FileText, color: '#a3a3a3' },
  '.env': { Icon: Settings, color: '#ecd53f' },
  '.gitignore': { Icon: SiGit, color: '#F05032' },
  '.gitattributes': { Icon: SiGit, color: '#F05032' },
  deno: { Icon: SiDeno, color: '#70FFAF' },
  bun: { Icon: SiBun, color: '#FBF0DF' },
  dockerignore: { Icon: SiDocker, color: '#2496ED' },
  'compose.yml': { Icon: SiDocker, color: '#2496ED' },
  'compose.yaml': { Icon: SiDocker, color: '#2496ED' },
  'docker-compose.yml': { Icon: SiDocker, color: '#2496ED' },
  'docker-compose.yaml': { Icon: SiDocker, color: '#2496ED' },
  gemfile: { Icon: SiRuby, color: '#CC342D' },
  'gemfile.lock': { Icon: SiRuby, color: '#CC342D' },
  rakefile: { Icon: SiRuby, color: '#CC342D' },
  '.ruby-version': { Icon: SiRuby, color: '#CC342D' },
  'package.json': { Icon: SiNpm, color: '#CB3837' },
  'package-lock.json': { Icon: SiNpm, color: '#CB3837' },
  'yarn.lock': { Icon: SiYarn, color: '#2C8EBB' },
  'pnpm-lock.yaml': { Icon: SiPnpm, color: '#F69220' },
  'tsconfig.json': { Icon: SiTypescript, color: '#3178C6' },
  'jsconfig.json': { Icon: SiJavascript, color: '#F7DF1E' },
  'vite.config.js': { Icon: SiVite, color: '#646CFF' },
  'vite.config.ts': { Icon: SiVite, color: '#646CFF' },
  'vite.config.mjs': { Icon: SiVite, color: '#646CFF' },
  'vite.config.cjs': { Icon: SiVite, color: '#646CFF' },
  'vitest.config.ts': { Icon: SiVitest, color: '#6E9F18' },
  'vitest.config.js': { Icon: SiVitest, color: '#6E9F18' },
  'vitest.config.mjs': { Icon: SiVitest, color: '#6E9F18' },
  'next.config.js': { Icon: SiNextdotjs, color: '#000000' },
  'next.config.mjs': { Icon: SiNextdotjs, color: '#000000' },
  'next.config.ts': { Icon: SiNextdotjs, color: '#000000' },
  'astro.config.mjs': { Icon: SiAstro, color: '#FF5D01' },
  'astro.config.ts': { Icon: SiAstro, color: '#FF5D01' },
  'svelte.config.js': { Icon: SiSvelte, color: '#FF3E00' },
  'svelte.config.cjs': { Icon: SiSvelte, color: '#FF3E00' },
  'tailwind.config.js': { Icon: SiTailwindcss, color: '#06B6D4' },
  'tailwind.config.ts': { Icon: SiTailwindcss, color: '#06B6D4' },
  'tailwind.config.cjs': { Icon: SiTailwindcss, color: '#06B6D4' },
  'postcss.config.js': { Icon: SiPostcss, color: '#DD3A0A' },
  'postcss.config.cjs': { Icon: SiPostcss, color: '#DD3A0A' },
  'webpack.config.js': { Icon: SiWebpack, color: '#1C78C0' },
  'webpack.config.ts': { Icon: SiWebpack, color: '#1C78C0' },
  '.babelrc': { Icon: SiBabel, color: '#F9DC3E' },
  'babel.config.js': { Icon: SiBabel, color: '#F9DC3E' },
  'babel.config.json': { Icon: SiBabel, color: '#F9DC3E' },
  'babel.config.cjs': { Icon: SiBabel, color: '#F9DC3E' },
  '.eslintrc': { Icon: SiEslint, color: '#4B32C3' },
  '.eslintrc.js': { Icon: SiEslint, color: '#4B32C3' },
  '.eslintrc.json': { Icon: SiEslint, color: '#4B32C3' },
  '.eslintrc.cjs': { Icon: SiEslint, color: '#4B32C3' },
  '.eslintrc.yml': { Icon: SiEslint, color: '#4B32C3' },
  '.eslintrc.yaml': { Icon: SiEslint, color: '#4B32C3' },
  'eslint.config.js': { Icon: SiEslint, color: '#4B32C3' },
  'eslint.config.mjs': { Icon: SiEslint, color: '#4B32C3' },
  'eslint.config.cjs': { Icon: SiEslint, color: '#4B32C3' },
  '.prettierrc': { Icon: SiPrettier, color: '#F7B93E' },
  '.prettierrc.json': { Icon: SiPrettier, color: '#F7B93E' },
  '.prettierrc.yaml': { Icon: SiPrettier, color: '#F7B93E' },
  '.prettierrc.yml': { Icon: SiPrettier, color: '#F7B93E' },
  '.prettierrc.js': { Icon: SiPrettier, color: '#F7B93E' },
  'prettier.config.js': { Icon: SiPrettier, color: '#F7B93E' },
  '.editorconfig': { Icon: SiEditorconfig, color: '#E0E0E0' },
  '.gitlab-ci.yml': { Icon: SiGitlab, color: '#FC6D26' },
  jenkinsfile: { Icon: SiJenkins, color: '#D24939' },
  'requirements.txt': { Icon: SiPython, color: '#3776AB' },
  'setup.py': { Icon: SiPython, color: '#3776AB' },
  'setup.cfg': { Icon: SiPython, color: '#3776AB' },
  'pyproject.toml': { Icon: SiPython, color: '#3776AB' },
  pipfile: { Icon: SiPython, color: '#3776AB' },
  'pipfile.lock': { Icon: SiPython, color: '#3776AB' },
  'tox.ini': { Icon: SiPython, color: '#3776AB' },
  'cargo.toml': { Icon: SiRust, color: '#DEA584' },
  'cargo.lock': { Icon: SiRust, color: '#DEA584' },
  'go.mod': { Icon: SiGo, color: '#00ADD8' },
  'go.sum': { Icon: SiGo, color: '#00ADD8' },
  'go.work': { Icon: SiGo, color: '#00ADD8' },
  'composer.json': { Icon: SiPhp, color: '#777BB4' },
  'composer.lock': { Icon: SiPhp, color: '#777BB4' },
  'mix.exs': { Icon: SiElixir, color: '#4B275F' },
  'mix.lock': { Icon: SiElixir, color: '#4B275F' },
  'package.swift': { Icon: SiSwift, color: '#F05138' },
  'project.clj': { Icon: SiClojure, color: '#5881D8' },
  'deps.edn': { Icon: SiClojure, color: '#5881D8' },
  'pubspec.yaml': { Icon: SiDart, color: '#0175C2' },
  'pubspec.lock': { Icon: SiDart, color: '#0175C2' },
  'elm.json': { Icon: SiElm, color: '#60B5CC' },
  'shard.yml': { Icon: SiCrystal, color: '#000000' },
  'deno.json': { Icon: SiDeno, color: '#70FFAF' },
  'deno.jsonc': { Icon: SiDeno, color: '#70FFAF' },
  '.npmrc': { Icon: SiNpm, color: '#CB3837' },
  '.yarnrc': { Icon: SiYarn, color: '#2C8EBB' },
  '.yarnrc.yml': { Icon: SiYarn, color: '#2C8EBB' },
  '.nvmrc': { Icon: SiNodedotjs, color: '#339933' },
  '.node-version': { Icon: SiNodedotjs, color: '#339933' },
  'gulpfile.js': { Icon: SiGulp, color: '#CF4647' },
  'gulpfile.mjs': { Icon: SiGulp, color: '#CF4647' },
  'gulpfile.ts': { Icon: SiGulp, color: '#CF4647' },
  'gruntfile.js': { Icon: SiGrunt, color: '#FAA918' },
  'gruntfile.cjs': { Icon: SiGrunt, color: '#FAA918' },
  'electron-builder.yml': { Icon: SiElectron, color: '#47848F' },
  'electron.vite.config.ts': { Icon: SiElectron, color: '#47848F' },
  '_config.yml': { Icon: SiJekyll, color: '#CC0000' },
  'docusaurus.config.js': { Icon: SiDocusaurus, color: '#3ECC5F' },
  'docusaurus.config.ts': { Icon: SiDocusaurus, color: '#3ECC5F' },
  'gatsby-config.js': { Icon: SiGatsby, color: '#663399' },
  'gatsby-config.ts': { Icon: SiGatsby, color: '#663399' },
  'gatsby-node.js': { Icon: SiGatsby, color: '#663399' },
  'remix.config.js': { Icon: SiRemix, color: '#3992FF' },
  'hugo.toml': { Icon: SiHugo, color: '#FF4088' },
  'hugo.yaml': { Icon: SiHugo, color: '#FF4088' }
}

function getFileIcon(name: string): IconConfig {
  const lowerName = name.toLowerCase()
  if (filenameMap[lowerName]) return filenameMap[lowerName]

  const ext = lowerName.split('.').pop()
  if (ext && iconMap[ext]) return iconMap[ext]

  return { Icon: File, color: 'var(--ctp-subtext0)' }
}

function getLuminance(hex: string): number {
  const r = parseInt(hex.slice(1, 3), 16) / 255
  const g = parseInt(hex.slice(3, 5), 16) / 255
  const b = parseInt(hex.slice(5, 7), 16) / 255
  const lin = (c: number): number => (c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4))
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)
}

function getIconColor(color: string): string {
  if (color.startsWith('var(')) return color
  const luminance = getLuminance(color)
  const mixPercent = luminance < 0.1 || luminance > 0.85 ? 55 : 30
  return `color-mix(in srgb, var(--ctp-text) ${mixPercent}%, ${color})`
}

const FileIcon = memo(function FileIcon({ name }: { name: string }) {
  const { Icon, color } = getFileIcon(name)
  return <Icon size={15} style={{ color: getIconColor(color) }} />
})

export default FileIcon
